/**
 * Repository-owned demo course notes. This text was written for BloomScroll
 * (no copyrighted textbook content) and is the single source of truth for:
 *   1. the demo document chunks shown in the source drawer,
 *   2. the demo PDFs generated by scripts/generate-demo-pdfs.ts, and
 *   3. the excerpts cited by demo study cards (verified by unit test to be
 *      exact substrings of this text).
 *
 * Math notation is kept ASCII-friendly (e.g. "w" for angular frequency) so
 * the generated PDFs can use standard fonts without glyph loss.
 */

export interface DemoPage {
  pageNumber: number;
  heading: string;
  body: string;
}

export interface DemoDocContent {
  id: string;
  title: string;
  filename: string;
  subject: string;
  pages: DemoPage[];
}

export const OS_NOTES: DemoDocContent = {
  id: "demo-doc-os",
  title: "Operating Systems — Course Notes",
  filename: "operating-systems-notes.pdf",
  subject: "Operating Systems",
  pages: [
    {
      pageNumber: 1,
      heading: "Processes and Programs",
      body: "A program is a passive artifact: instructions and static data sitting in a file. A process is that program in motion, with a program counter, registers, a stack, a heap, and open file descriptors. The operating system tracks each process in a process control block (PCB), which records the process identifier, scheduling state, saved CPU context, and accounting information. Because the PCB captures everything needed to resume execution, the kernel can pause a process and continue it later as if nothing happened. Processes move through a small set of states: new, ready, running, waiting, and terminated. Only one process per core is running at a time; the ready queue holds processes that could run immediately if given a core, while waiting processes are blocked on some event such as disk input or a timer.",
    },
    {
      pageNumber: 2,
      heading: "Threads and Context Switching",
      body: "Threads are execution streams that live inside a process and share its address space, open files, and global data, while keeping private stacks and register state. Sharing an address space makes communication between threads cheap, but it also means one careless write can corrupt data another thread is using. Creating a thread is far cheaper than creating a process because no new address space must be built. A context switch is the act of saving the current execution context into its PCB or thread control block and loading another. Switches are pure overhead: the machine spends cycles on bookkeeping and, worse, loses cache and TLB warmth, so the freshly scheduled thread starts by missing in caches it used to own. Schedulers therefore try to balance responsiveness against switching too often.",
    },
    {
      pageNumber: 3,
      heading: "CPU Scheduling Basics",
      body: "The scheduler decides which ready process runs next. Common metrics are turnaround time (submission to completion), waiting time (time spent in the ready queue), and response time (submission to first output). First-come-first-served (FCFS) is simple but suffers from the convoy effect: one long job makes every short job behind it wait. Shortest-job-first (SJF) provably minimizes average waiting time, because moving a short job ahead of a long one reduces the waiting time of the short job by more than it increases the waiting time of the long one. The catch is that run times are not known in advance, so real systems estimate them from history. Preemptive schedulers may interrupt a running process when a better candidate arrives; non-preemptive schedulers wait for the process to yield.",
    },
    {
      pageNumber: 4,
      heading: "Round-Robin and Multilevel Feedback",
      body: "Round-robin scheduling gives each process a fixed time quantum and cycles through the ready queue. The quantum is a tuning knob: a very large quantum degrades round-robin into FCFS, while a very small quantum makes the system spend most of its time context switching instead of doing useful work. A common rule of thumb is to size the quantum so that most interactive bursts finish within it. The multilevel feedback queue (MLFQ) refines this idea with several queues of different priority. New jobs start in the top queue; jobs that consume their full quantum are demoted, while jobs that block early stay high priority. In effect MLFQ learns each job's behavior: interactive jobs remain responsive, and long CPU-bound jobs sink to lower queues where they run with larger quanta.",
    },
    {
      pageNumber: 5,
      heading: "Virtual Memory and Paging",
      body: "Virtual memory gives every process the illusion of a large, private, contiguous address space, decoupling the addresses a program uses from the physical RAM that backs them. Under paging, the virtual address space is divided into fixed-size pages, and physical memory into frames of the same size. A per-process page table maps each virtual page to a physical frame, along with permission bits and a valid bit. This indirection buys three things: processes are protected from each other because they simply cannot name each other's frames; memory need not be contiguous, which ends external fragmentation; and pages can live on disk until they are actually touched, allowing programs larger than physical memory to run.",
    },
    {
      pageNumber: 6,
      heading: "The TLB and Page Faults",
      body: "Walking a page table on every memory access would double or triple memory traffic, so processors keep a translation lookaside buffer (TLB), a small cache of recent virtual-to-physical translations. Because programs exhibit locality, a small TLB catches the overwhelming majority of translations, making paging affordable in practice. When a program touches a page whose valid bit is clear, the hardware raises a page fault and traps to the kernel. Under demand paging, the kernel finds the page's contents (on disk, or zero-filled for new allocations), picks a free frame, updates the page table, and restarts the faulting instruction. The process is unaware anything happened except time passed. Faults that reference truly invalid addresses instead terminate the process with a segmentation fault.",
    },
    {
      pageNumber: 7,
      heading: "Page Replacement",
      body: "When memory is full, bringing a page in means choosing a victim page to evict. First-in-first-out (FIFO) evicts the oldest resident page, but it can behave badly: Belady's anomaly shows that with FIFO, giving a workload more frames can actually increase the number of page faults. Least-recently-used (LRU) evicts the page untouched for the longest time, on the theory that the recent past predicts the near future. True LRU is expensive in hardware, so real systems approximate it with the clock algorithm: pages sit on a circular list with a reference bit, and the clock hand clears bits as it sweeps, evicting the first page it finds whose bit is already clear. A page's reference bit thus acts as a one-bit memory of recent use.",
    },
    {
      pageNumber: 8,
      heading: "Concurrency, Races, and Locks",
      body: "A race condition occurs when the result of a computation depends on the timing of concurrent threads. The classic example is two threads incrementing a shared counter: each performs load, add, store, and if the operations interleave, one increment is lost. The code region that touches shared state is a critical section, and correctness requires mutual exclusion: at most one thread inside at a time. A mutex (lock) provides this: threads acquire the lock before entering and release it after leaving; a thread that finds the lock held must wait. Locks restore atomicity, meaning the section appears to execute as one indivisible step. The costs are potential waiting, the risk of forgetting a lock, and the risk of deadlock when multiple locks interact.",
    },
    {
      pageNumber: 9,
      heading: "Deadlock",
      body: "Deadlock is a cycle of threads each waiting for a resource the next one holds, so none can proceed. Four conditions must all hold: mutual exclusion (resources cannot be shared), hold and wait (a thread keeps what it has while waiting for more), no preemption (resources cannot be forcibly taken), and circular wait (a cycle of waiters exists). Break any one condition and deadlock is impossible. The most practical strategy is to break circular wait by imposing a global lock ordering: if every thread acquires locks in the same agreed order, a cycle of waiters cannot form. Deadlock avoidance schemes such as the banker's algorithm instead keep the system in states from which all threads can still finish, but they require knowing maximum demands in advance, which is rare.",
    },
    {
      pageNumber: 10,
      heading: "File Systems and Inodes",
      body: "A file system maps human-friendly names onto blocks of storage. In Unix-style designs, a file's metadata lives in an inode: size, permissions, timestamps, and pointers to the data blocks. Crucially, the inode does not contain the file's name. Directories are themselves small files holding name-to-inode-number entries, which is why a single inode can be reached by several names (hard links) and why renaming a file does not move its data. Small files are reached directly through the inode's direct pointers, while large files use indirect blocks: pointers to blocks of pointers. Journaling file systems write an intent record to a log before updating metadata in place, so that after a crash, recovery replays or discards whole operations instead of leaving the tree half-updated.",
    },
  ],
};

export const SS_NOTES: DemoDocContent = {
  id: "demo-doc-ss",
  title: "Signals & Systems — Course Notes",
  filename: "signals-and-systems-notes.pdf",
  subject: "Signals & Systems",
  pages: [
    {
      pageNumber: 1,
      heading: "Signals: Continuous and Discrete",
      body: "A signal is a function carrying information: a voltage over time, a brightness over space, a daily temperature over days. Continuous-time signals x(t) are defined for every real t; discrete-time signals x[n] are defined only at integer n, usually because something sampled an underlying quantity. Two tiny signals do outsized work. The unit impulse (delta) is the idealized instant of energy at time zero: in discrete time, delta[n] equals 1 at n = 0 and 0 elsewhere. The unit step u[n] is 0 before time zero and 1 after, and it switches things on. Any discrete signal can be written as a sum of scaled, shifted impulses, which is exactly why the impulse is the right probe for studying systems.",
    },
    {
      pageNumber: 2,
      heading: "System Properties",
      body: "A system transforms an input signal into an output signal. A system is linear when scaling and adding inputs scales and adds outputs the same way: superposition holds. It is time-invariant when the system behaves the same today as tomorrow: shifting the input only shifts the output. It is causal when the output at any time depends only on present and past inputs, never future ones, which every real-time physical system must satisfy. It is BIBO stable when every bounded input produces a bounded output, so the system cannot blow up in response to a finite disturbance. These properties matter because the intersection of the first two, the LTI system, admits a complete and elegant theory that the rest of the course builds on.",
    },
    {
      pageNumber: 3,
      heading: "LTI Systems and the Impulse Response",
      body: "For a linear time-invariant system, one measurement characterizes everything: the impulse response h, the output produced when the input is a unit impulse. The reasoning is direct. Any input can be decomposed into scaled, shifted impulses. Time invariance says a shifted impulse produces a shifted copy of h. Linearity says a weighted sum of impulses produces the same weighted sum of responses. Therefore the output for any input is completely determined by h; there is nothing else to know about the system. Two useful facts follow immediately: an LTI system is causal exactly when h is zero for negative time, and it is BIBO stable exactly when h is absolutely summable (or absolutely integrable in continuous time).",
    },
    {
      pageNumber: 4,
      heading: "Convolution",
      body: "The recipe from the previous section has a name: convolution. In discrete time, y[n] = sum over k of x[k] h[n - k], written y = x * h. Each input sample launches its own scaled, shifted copy of the impulse response, and the output at time n is the sum of all the echoes arriving at that moment. Convolution is commutative (x * h = h * x), associative, and distributive over addition, so cascaded LTI systems can be collapsed into a single system whose impulse response is the convolution of the stages, in any order. A helpful special case: convolving a signal with a shifted impulse delta[n - d] simply delays the signal by d samples, nothing more.",
    },
    {
      pageNumber: 5,
      heading: "Fourier Series",
      body: "A periodic signal with period T can be written as a sum of harmonically related complex exponentials: sinusoids at the fundamental frequency 1/T and integer multiples of it. The Fourier series coefficients say how much of each harmonic the signal contains, and they are found by correlating the signal against each harmonic over one period. Smooth signals need few harmonics; signals with sharp edges need many, because edges are built from rapidly oscillating components. This is more than a curiosity: complex exponentials are eigenfunctions of LTI systems, meaning a sinusoid in yields a sinusoid out at the same frequency, only rescaled and phase-shifted. Decomposing into sinusoids therefore turns an LTI system into simple per-frequency multiplication.",
    },
    {
      pageNumber: 6,
      heading: "The Fourier Transform",
      body: "Aperiodic signals get the same treatment by letting the period grow without bound; the discrete set of harmonics merges into a continuum. The Fourier transform X(jw) = integral of x(t) e^(-jwt) dt measures how much of each frequency w the signal contains, and the inverse transform rebuilds x(t) from its spectrum. The pair reveals a signal's frequency content: where its energy lives, how fast it can change, how wide its bandwidth is. Key properties carry the load in practice: convolution in time becomes multiplication in frequency, a time shift becomes a phase ramp, and time-scaling a signal inversely scales its spectrum, which is the precise version of the slogan that short events are wideband.",
    },
    {
      pageNumber: 7,
      heading: "Frequency Response and Filtering",
      body: "Feeding e^(jwt) into an LTI system returns H(jw) e^(jwt), where H(jw), the frequency response, is the Fourier transform of the impulse response. For a sinusoidal input, the magnitude |H(jw)| multiplies the amplitude and the angle of H(jw) adds to the phase; the frequency itself never changes. This single fact is the basis of filtering. A low-pass filter has |H| near 1 at low frequencies and near 0 at high frequencies, keeping slow trends while discarding rapid wiggles; a high-pass filter does the opposite, and a band-pass filter keeps a chosen band. Designing a filter is choosing an achievable H(jw) that treats the frequencies you care about gently and the frequencies you don't harshly.",
    },
    {
      pageNumber: 8,
      heading: "Sampling and Aliasing",
      body: "Sampling reads a continuous signal every Ts seconds, producing x[n] = x(nTs) at sampling rate fs = 1/Ts. The sampling theorem gives the exact condition for losing nothing: if x(t) contains no frequencies above B, then sampling at fs greater than 2B (the Nyquist rate) allows perfect reconstruction of x(t) from its samples. Sample too slowly and aliasing occurs: frequencies above fs/2 are folded down and masquerade as lower frequencies, indistinguishable from genuine ones once the samples are taken. This is why a wagon wheel appears to spin backwards on film. Practical systems therefore place an anti-aliasing low-pass filter before the sampler, removing content above fs/2 so that what remains is sampled faithfully.",
    },
    {
      pageNumber: 9,
      heading: "The Laplace Transform",
      body: "The Laplace transform X(s) = integral of x(t) e^(-st) dt generalizes the Fourier transform by using the complex frequency s = sigma + jw, which handles growing and decaying signals that have no Fourier transform. Each transform comes with a region of convergence (ROC), the set of s where the integral exists; the same algebraic X(s) with different ROCs describes different signals. For systems described by linear differential equations, the transfer function H(s) is a ratio of polynomials, and its poles, the roots of the denominator, control behavior. A causal system is stable exactly when all poles lie strictly in the left half of the s-plane, because each pole contributes a mode e^(pt) that decays only when the pole's real part is negative.",
    },
    {
      pageNumber: 10,
      heading: "The Z-Transform",
      body: "Discrete-time systems get the same machinery through the z-transform, X(z) = sum of x[n] z^(-n). The unit circle in the z-plane plays the role the imaginary axis plays for Laplace: evaluating X(z) on the unit circle gives the discrete-time Fourier transform, when it exists. For a causal discrete LTI system with rational transfer function H(z), stability requires every pole to lie strictly inside the unit circle, since each pole p contributes a mode p^n that decays only when the magnitude of p is less than 1. Digital filter design is largely the art of placing poles and zeros in the z-plane: poles near the unit circle create resonant peaks, and zeros on the circle carve out notches at chosen frequencies.",
    },
  ],
};

export const DEMO_DOCS: DemoDocContent[] = [OS_NOTES, SS_NOTES];
